export interface FluxEvent { event_id: number | null; type: string; payload: Record<string, unknown>; created_at?: string | null; }
export type FluxConnectionState = "idle" | "connecting" | "open" | "reconnecting" | "closed" | "error";
export interface FluxTaskSnapshot { task_id: string; status: string; task?: string; result?: Record<string, unknown> | null; error?: string | null; }
export interface FluxTaskSummary { task_id: string; task: string; status: string; branch?: string; started_at?: string | null; finished_at?: string | null; final_response?: string; errors?: string[]; pull_request?: Record<string, unknown> | null; review?: Record<string, unknown> | null; }
type Requester = (path: string, init?: RequestInit) => Promise<Response>;

export interface FluxTaskClientOptions { baseUrl?: string; request?: Requester; onConnection?: (state: FluxConnectionState) => void; onEvent?: (event: FluxEvent) => void; onError?: (error: Error) => void; }
function apiUrl(base: string, path: string) { return `${base.replace(/\/$/, "")}${path}`; }

export class FluxTaskClient {
  private readonly baseUrl: string; private readonly request?: Requester; private readonly options: FluxTaskClientOptions;
  private abort: AbortController | null = null; private disposed = false; private taskId: string | null = null; private lastEventId = 0; private reconnectTimer: ReturnType<typeof setTimeout> | null = null; private reconnectAttempt = 0;
  constructor(options: FluxTaskClientOptions = {}) { this.baseUrl = options.baseUrl ?? (import.meta.env.VITE_KYREX_CLOUD_URL || ""); this.request = options.request; this.options = options; }
  get currentTaskId() { return this.taskId; } get cursor() { return this.lastEventId; }
  async submit(task: string): Promise<FluxTaskSnapshot> { if (!this.baseUrl || !task.trim()) throw new Error("Cloud task is not configured"); const response = await (this.request ?? fetch)(apiUrl(this.baseUrl, "/api/task"), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ task: task.trim() }) }); if (!response.ok) throw new Error(`Cloud task submission failed (${response.status})`); const snapshot = await response.json() as FluxTaskSnapshot; this.taskId = snapshot.task_id; this.lastEventId = 0; this.connect(); return snapshot; }
  connect(taskId = this.taskId) { if (!taskId || this.disposed) return; this.taskId = taskId; this.abort?.abort(); this.abort = new AbortController(); this.options.onConnection?.(this.reconnectAttempt ? "reconnecting" : "connecting"); this.tail(taskId, this.abort.signal); }
  private async tail(taskId: string, signal: AbortSignal) { const query = this.lastEventId > 0 ? `?after=${encodeURIComponent(this.lastEventId)}` : ""; try { const response = await (this.request ?? fetch)(apiUrl(this.baseUrl, `/api/task/${encodeURIComponent(taskId)}/events${query}`), { signal, headers: { Accept: "text/event-stream" } }); if (!response.ok || !response.body) throw new Error(`Cloud event stream failed (${response.status})`); this.reconnectAttempt = 0; this.options.onConnection?.("open"); await this.parseStream(response.body, signal); } catch (error) { if (signal.aborted || this.disposed) return; this.options.onError?.(error instanceof Error ? error : new Error(String(error))); this.options.onConnection?.("reconnecting"); this.scheduleReconnect(); } }
  private async parseStream(body: ReadableStream<Uint8Array>, signal: AbortSignal) { const reader = body.getReader(); const decoder = new TextDecoder(); let buffer = ""; while (!signal.aborted) { const chunk = await reader.read(); if (chunk.done) break; buffer += decoder.decode(chunk.value, { stream: true }); const frames = buffer.split(/\r?\n\r?\n/); buffer = frames.pop() ?? ""; for (const frame of frames) this.handleFrame(frame); } }
  private handleFrame(frame: string) { let id: number | null = null; let type = "message"; const data: string[] = []; for (const line of frame.split(/\r?\n/)) { if (line.startsWith("id:")) id = Number(line.slice(3).trim()); else if (line.startsWith("event:")) type = line.slice(6).trim(); else if (line.startsWith("data:")) data.push(line.slice(5).trimStart()); } if (!data.length) return; try { const payload = JSON.parse(data.join("\n")) as Record<string, unknown>; const event = { event_id: id !== null && Number.isFinite(id) ? id : null, type, payload }; if (event.event_id !== null && event.event_id > this.lastEventId) this.lastEventId = event.event_id; this.options.onEvent?.(event); if (type === "end") { this.abort?.abort(); this.options.onConnection?.("closed"); } } catch { this.options.onError?.(new Error("Flux returned invalid JSON event data")); } }
  private scheduleReconnect() { if (this.reconnectTimer) clearTimeout(this.reconnectTimer); const delay = Math.min(1000 * 2 ** this.reconnectAttempt++, 10000); this.reconnectTimer = setTimeout(() => this.connect(), delay); }
  /** Fetch the durable task snapshot for *taskId* (GET /api/task/{id}). */
  async get(taskId: string): Promise<FluxTaskSnapshot> { if (!this.baseUrl) throw new Error("Cloud task is not configured"); const response = await (this.request ?? fetch)(apiUrl(this.baseUrl, `/api/task/${encodeURIComponent(taskId)}`), { headers: { Accept: "application/json" } }); if (!response.ok) throw new Error(`Cloud task lookup failed (${response.status})`); return await response.json() as FluxTaskSnapshot; }
  /** Request cancellation of a task (POST /api/task/{id}/cancel). */
  async cancel(taskId = this.taskId): Promise<{ requested: boolean; status: string }> { if (!this.baseUrl || !taskId) throw new Error("Cloud task is not configured"); const response = await (this.request ?? fetch)(apiUrl(this.baseUrl, `/api/task/${encodeURIComponent(taskId)}/cancel`), { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }); if (!response.ok) throw new Error(`Cloud task cancel failed (${response.status})`); return await response.json() as { requested: boolean; status: string }; }
  /** List recent tasks for the authenticated user (GET /api/results). */
  async listResults(): Promise<FluxTaskSummary[]> { if (!this.baseUrl) throw new Error("Cloud task is not configured"); const response = await (this.request ?? fetch)(apiUrl(this.baseUrl, "/api/results"), { headers: { Accept: "application/json" } }); if (!response.ok) throw new Error(`Cloud results failed (${response.status})`); const body = await response.json() as { results?: FluxTaskSummary[] }; return body.results ?? []; }
  /** Follow an existing task's stream from the beginning (cursor reset). */
  follow(taskId: string) { if (!taskId || this.disposed) return; this.taskId = taskId; this.lastEventId = 0; this.reconnectAttempt = 0; this.connect(); }
  dispose() { this.disposed = true; if (this.reconnectTimer) clearTimeout(this.reconnectTimer); this.abort?.abort(); this.options.onConnection?.("closed"); }
}
